exclude_paths:
  - '/node_modules/*'
  - '/vendor/*'

engines:
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: 'php'
      standard: 'PSR1,PSR2'
  phpmd:
    enabled: true
    config:
      file_extensions: 'php'
      rulesets: 'cleancode,codesize,design,naming,unusedcode'

ratings:
  paths:
    - 'build/**.js'
    - 'build/**.php'
